apiVersion: v1
kind: Secret
metadata:
  name: amazing-secrets
  namespace: amazing
type: Opaque
stringData:
  DB_PASSWORD: "amazing123"
  JWT_SECRET: "change-me-in-production"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin123"
  GRAFANA_PASSWORD: "admin123"
