apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: amazing
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: python-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: amazing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: amazing/python-api:latest
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: amazing-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
